name: Build and Publish NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show commit info
        run: |
          echo "Current commit SHA: ${{ github.sha }}"
          git log -1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects except excluded ones
        run: |
          for proj in $(find . -name "*.csproj" ! -path "*/Jobs.ImageProcessing.Workers/*" ! -path "*/Jobs.ImageProcess.UploadValidation/*"); do
            echo "Restoring $proj"
            dotnet restore "$proj"
          done
      
      - name: Clean all projects except excluded ones
        run: |
          for proj in $(find . -name "*.csproj" ! -path "*/Jobs.ImageProcessing.Workers/*" ! -path "*/Jobs.ImageProcess.UploadValidation/*"); do
            echo "Cleaning $proj"
            dotnet clean "$proj" --configuration Release
          done
      
      - name: Build all projects except excluded ones
        run: |
          for proj in $(find . -name "*.csproj" ! -path "*/Jobs.ImageProcessing.Workers/*" ! -path "*/Jobs.ImageProcess.UploadValidation/*"); do
            echo "Building $proj"
            dotnet build "$proj" --configuration Release --no-restore
          done
  
      - name: Pack JobManagement.Sdk and JobManagement.DataAccess with auto-incremented version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "Packaging with version $VERSION"
          # Package JobManagement.Sdk
          dotnet pack ./JobManagement.Sdk/JobManagement.Sdk.csproj \
            --configuration Release \
            -p:PackageVersion=$VERSION \
            --output ./artifacts
          # Package JobManagement.DataAccess
          dotnet pack ./JobManagement.DataAccess/JobManagement.DataAccess.csproj \
            --configuration Release \
            -p:PackageVersion=$VERSION \
            --output ./artifacts
      
      - name: Publish to GitHub Packages and NuGet.org
        run: |
          for nupkg in ./artifacts/*.nupkg; do
            echo "Publishing $nupkg to GitHub Packages"
            dotnet nuget push "$nupkg" \
              --source "https://nuget.pkg.github.com/pawd-app/index.json" \
              --api-key ${{ secrets.TOKEN }} \
              --skip-duplicate
            echo "Publishing $nupkg to NuGet.org"
            dotnet nuget push "$nupkg" \
              --source "https://api.nuget.org/v3/index.json" \
              --api-key ${{ secrets.NUGET_ORG_API_KEY }} \
              --skip-duplicate
          done

        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TOKEN }}
